# Generated by scripts/formula.ts — do not edit by hand.
class Druk < Formula
  desc "Terminal code editor"
  homepage "https://github.com/letstri/druk"
  version "1.20.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/letstri/druk/releases/download/v1.20.3/druk-darwin-arm64.zip"
      sha256 "bf413ca7dbf44e635db81f24f672e232f8cd5ab46ef660c6c556612454cdea3d"
    end
    on_intel do
      url "https://github.com/letstri/druk/releases/download/v1.20.3/druk-darwin-x64.zip"
      sha256 "1516ffc5e5786d64bf0674338488a557dda999de1c8b42dc478f6556d2dff8ec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/letstri/druk/releases/download/v1.20.3/druk-linux-arm64.tar.gz"
      sha256 "1035a64bbe957f3cf4772e2df1041d8133755065c8b7fd0f2bd3556933938861"
    end
    on_intel do
      url "https://github.com/letstri/druk/releases/download/v1.20.3/druk-linux-x64.tar.gz"
      sha256 "e5586556f124c439fa31084efffe8037495706d362fe53d0cb95151196c07ae2"
    end
  end

  bottle do
    root_url "https://github.com/letstri/druk/releases/download/v1.20.3"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "26a05e575a432f57baa47d876dbdb355327df46cb6900dc02fe00615f228b33e"
    sha256 cellar: :any_skip_relocation, ventura: "29b5bcd9d4b3f9a2194e7a93f7569219bca28331782b8399916f3d6e5696f5fe"
    sha256 cellar: :any_skip_relocation, arm64_linux: "9dd222ae15830e3fac9b720e951f2d4fa926b9d5f0433df621ba08a48bb55a4b"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "2ee3591b41fe99fed975542f42d091cd15a8a723ae17b3916dbbe10546686b47"
  end

  def install
    bin.install "druk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/druk --version")
  end
end
