# Generated by scripts/formula.ts — do not edit by hand.
class Druk < Formula
  desc "Terminal code editor"
  homepage "https://github.com/letstri/druk"
  version "1.35.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/letstri/druk/releases/download/v1.35.2/druk-darwin-arm64.zip"
      sha256 "9e6da6f32c73ea138a351c8fbf48dcfb1d971ef0e50d3424a5e61dc550e1fa6f"
    end
    on_intel do
      url "https://github.com/letstri/druk/releases/download/v1.35.2/druk-darwin-x64.zip"
      sha256 "7ad6cbcc00eb0dbf35bfe6d46a5e8f7ea8de1097827bda501100d873c257e947"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/letstri/druk/releases/download/v1.35.2/druk-linux-arm64.tar.gz"
      sha256 "a099d9f28a94e38623470bb14341fd2d5ee42f9b1f152d58c321030864db3a42"
    end
    on_intel do
      url "https://github.com/letstri/druk/releases/download/v1.35.2/druk-linux-x64.tar.gz"
      sha256 "d669c09bcdab43f4f15638c18cb6fbdb0b75cc4e4757ab0a13cb36cf79d0f250"
    end
  end

  bottle do
    root_url "https://github.com/letstri/druk/releases/download/v1.35.2"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "8fb860da16bd7399ce0a724e816b18197f36ab3bd4d5d8741531b35db10f42ba"
    sha256 cellar: :any_skip_relocation, ventura: "9749d4a757975adb17fdac5da9fa5991c87b9579f859717d085ad84a238aa4eb"
    sha256 cellar: :any_skip_relocation, arm64_linux: "79d6e75ff811750f9ec31d4078b4aa1f70dd875425e4783f485167487befdb11"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "b6e3c75773efc4fb61f5856ca6c416bdd5172265c1dd91e308b772fa21367440"
  end

  def install
    bin.install "druk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/druk --version")
  end
end
