# Generated by scripts/formula.ts — do not edit by hand.
class Druk < Formula
  desc "Terminal code editor"
  homepage "https://github.com/letstri/druk"
  version "1.31.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/letstri/druk/releases/download/v1.31.2/druk-darwin-arm64.zip"
      sha256 "accc557f2a8713e926ce26ab75961fe0e63a5c8f8a6e016be5df50b48b79aacf"
    end
    on_intel do
      url "https://github.com/letstri/druk/releases/download/v1.31.2/druk-darwin-x64.zip"
      sha256 "a452985c51c11576c3abb992f40a2691ff43a3edebb361d229573c908047ebf7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/letstri/druk/releases/download/v1.31.2/druk-linux-arm64.tar.gz"
      sha256 "a96893073367106352b7603a7cb724442e4258b97eb63c9ec5edc781b12c731e"
    end
    on_intel do
      url "https://github.com/letstri/druk/releases/download/v1.31.2/druk-linux-x64.tar.gz"
      sha256 "23ba5e9a2681a1ed9f48849368c581a3e60742f4a3eee616cad53bd68b79a5dc"
    end
  end

  bottle do
    root_url "https://github.com/letstri/druk/releases/download/v1.31.2"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "58590c55f4711b668b6ec29a43273d09594064a29acef7bb43ebdf9347b7bfea"
    sha256 cellar: :any_skip_relocation, ventura: "f4447b8e0a9d771b502976c26dffca7b8eb8d0d41f4a9350ded306005b20019e"
    sha256 cellar: :any_skip_relocation, arm64_linux: "a8e556ddf1fcab9f8298f0eaf47971ba2a0ea5b65d54040eb443a9d7a463b5b0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "94b98176f92897920a483e84c2cc17759363905584a7715d898df76110768c44"
  end

  def install
    bin.install "druk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/druk --version")
  end
end
